"""made some changes, include title now

Revision ID: ce66c81c9afc
Revises: d3f04d026fc0
Create Date: 2024-07-11 11:07:56.602783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce66c81c9afc'
down_revision = 'd3f04d026fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptimes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.alter_column('car',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('track',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=24),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptimes', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=24),
               nullable=False)
        batch_op.alter_column('track',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('car',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
