"""changes

Revision ID: 3930f8fb29bb
Revises: 398b531ece74
Create Date: 2024-06-12 19:00:08.231163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3930f8fb29bb'
down_revision = '398b531ece74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptimes', schema=None) as batch_op:
        batch_op.drop_constraint('laptimes_car_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('laptimes_driver_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('laptimes_track_id_fkey', type_='foreignkey')
        batch_op.drop_column('car_id')
        batch_op.drop_column('driver_id')
        batch_op.drop_column('track_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptimes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('laptimes_track_id_fkey', 'tracks', ['track_id'], ['id'])
        batch_op.create_foreign_key('laptimes_driver_id_fkey', 'drivers', ['driver_id'], ['id'])
        batch_op.create_foreign_key('laptimes_car_id_fkey', 'cars', ['car_id'], ['id'])

    # ### end Alembic commands ###
