"""changes

Revision ID: d04cf9a9ba42
Revises: 1f2005ae0666
Create Date: 2024-06-12 19:07:30.118672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04cf9a9ba42'
down_revision = '1f2005ae0666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptimes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('track', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('comment', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptimes', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('track')
        batch_op.drop_column('car')

    # ### end Alembic commands ###
