"""changes

Revision ID: fe210f840b73
Revises: d04cf9a9ba42
Create Date: 2024-06-12 19:35:04.473030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe210f840b73'
down_revision = 'd04cf9a9ba42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptimes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptimes', schema=None) as batch_op:
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
