name: Python Backend CI

on:
  push:
    branches:
      - '**' 

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PG: ${{ secrets.PG }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      TESTING_PG: ${{ secrets.TESTING_PG }}
      TESTING_JWT_SECRET_KEY: ${{ secrets.TESTING_JWT_SECRET_KEY }}
      TESTING_SECRET_KEY: ${{ secrets.TESTING_SECRET_KEY }}
      API_KEY: ${{ secrets.API_KEY }}
      FORMULA_1_KEY: ${{ secrets.FORMULA_1_KEY }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd tracknow/backend
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd tracknow/backend
          python -m pytest
    
      - name: Run tests with code coverage
        run: |
          cd tracknow/backend
          python -m pytest
          coverage run -m pytest
          coverage report -m
          coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}